# Generated by Django 4.1.7 on 2023-08-26 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("frate", "0121_delete_option"),
    ]

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "fill_method",
                    models.CharField(
                        choices=[
                            ("P", "Pick Up"),
                            ("T", "Trade"),
                            ("O", "Pick Up Into Overtime"),
                            ("B", "Break PTO"),
                            ("D", "Break TDO"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("preference", models.IntegerField(default=0)),
                ("must_trade", models.BooleanField(default=False)),
                ("week_hours", models.IntegerField(default=0)),
                ("period_hours", models.IntegerField(default=0)),
                ("entitled", models.BooleanField(default=False)),
                ("discrepancy", models.IntegerField(default=0)),
                ("marked_as_off", models.BooleanField(default=False)),
                ("is_viable", models.BooleanField(default=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="frate.employee",
                    ),
                ),
                (
                    "pay_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="frate.payperiod",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="frate.slot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Option",
                "verbose_name_plural": "Options",
                "ordering": ["slot", "-entitled", "-score"],
                "unique_together": {("employee", "slot")},
            },
        ),
    ]
