# Generated by Django 4.1.7 on 2023-08-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("options", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="abs_discrepancy",
            field=models.IntegerField(default=0),
        ),
    ]
