# Generated by Django 4.1.7 on 2023-08-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("options", "0002_option_abs_discrepancy"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="not_over_streak",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="option",
            name="streak",
            field=models.IntegerField(default=0),
        ),
    ]
