# Generated by Django 4.1.7 on 2023-06-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slotoption',
            options={'ordering': ['slot', 'employee']},
        ),
        migrations.AddField(
            model_name='schedule',
            name='employees',
            field=models.ManyToManyField(related_name='schedules', to='frate.employee'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='shifts',
            field=models.ManyToManyField(related_name='schedules', to='frate.shift'),
        ),
        migrations.AddField(
            model_name='shift',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
