# Generated by Django 4.1.7 on 2023-06-11 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTemplateSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_schedules', to='frate.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_schedules', to='frate.employee')),
            ],
            options={
                'ordering': ['status', 'department'],
            },
        ),
        migrations.AlterField(
            model_name='basetemplateslot',
            name='template_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_slots', to='frate.employeetemplateschedule'),
        ),
        migrations.DeleteModel(
            name='TemplateSchedule',
        ),
    ]
