# Generated by Django 4.1.7 on 2023-06-13 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0002_alter_slotoption_options_schedule_employees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tdoslot',
            name='version',
        ),
        migrations.RemoveField(
            model_name='tdoslot',
            name='workday',
        ),
        migrations.AddField(
            model_name='slot',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='frate.employee'),
        ),
        migrations.AddField(
            model_name='slot',
            name='slot_type',
            field=models.CharField(choices=[('S', 'Shift'), ('T', 'Templated Day Off'), ('P', 'Paid Time Off')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='slot',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='frate.shift'),
        ),
        migrations.DeleteModel(
            name='PtoSlot',
        ),
        migrations.DeleteModel(
            name='TdoSlot',
        ),
    ]
