# Generated by Django 4.1.7 on 2023-06-11 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0002_employeetemplateschedule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeetemplateschedule',
            options={'ordering': ['status', 'employee']},
        ),
        migrations.RemoveField(
            model_name='employeetemplateschedule',
            name='department',
        ),
    ]
