# Generated by Django 4.1.7 on 2023-06-11 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0003_alter_employeetemplateschedule_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basetemplateslot',
            name='mirroring',
        ),
        migrations.AddField(
            model_name='basetemplateslot',
            name='following',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='frate.basetemplateslot'),
        ),
    ]
