# Generated by Django 4.1.7 on 2023-06-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0004_alter_slot_unique_together_ptorequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetemplateslot',
            name='schedules',
            field=models.ManyToManyField(related_name='template_slots', to='frate.schedule'),
        ),
    ]
