# Generated by Django 4.1.7 on 2023-06-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0005_basetemplateslot_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotoption',
            name='level',
            field=models.CharField(choices=[('A', 'Assertive'), ('P', 'Preferred'), ('D', 'Deferent'), ('S', 'Swap In')], default='D', max_length=1),
        ),
    ]
