# Generated by Django 4.1.7 on 2023-06-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0006_slotoption_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotoption',
            name='level',
            field=models.CharField(choices=[('A', 'Assertive'), ('P', 'Preferred'), ('D', 'Deferent'), ('S', 'Swap In')], default='P', max_length=1),
        ),
    ]
