# Generated by Django 4.1.7 on 2023-06-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0008_slot_direct_template_slot_generic_templates_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['shift__start_time', 'workday__date']},
        ),
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
