# Generated by Django 4.1.7 on 2023-06-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0009_alter_shift_options_alter_slot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='img/'),
        ),
    ]
