# Generated by Django 4.1.7 on 2023-06-15 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0015_alter_department_icon_id_alter_shift_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phase_pref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='frate.timephase'),
        ),
    ]
