# Generated by Django 4.1.7 on 2023-06-17 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0016_employee_phase_pref'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleTemplateSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_count', models.PositiveSmallIntegerField()),
                ('role', models.CharField(max_length=50)),
                ('max_employees', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_template_schedules', to='frate.department')),
            ],
        ),
        migrations.CreateModel(
            name='RoleTemplateSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_id', models.PositiveSmallIntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_template_slots', to='frate.roletemplateschedule')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_template_slots', to='frate.shift')),
            ],
            options={
                'ordering': ['sd_id'],
            },
        ),
        migrations.AddField(
            model_name='roletemplateschedule',
            name='slots',
            field=models.ManyToManyField(related_name='role_templates', through='frate.RoleTemplateSlot', to='frate.shift'),
        ),
    ]
