# Generated by Django 4.1.7 on 2023-06-17 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0017_roletemplateschedule_roletemplateslot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleTemplateEmployeeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_template_relations', to='frate.employee')),
            ],
            options={
                'ordering': ['template_schedule', 'employee'],
            },
        ),
        migrations.RemoveField(
            model_name='roletemplateschedule',
            name='slots',
        ),
        migrations.AddField(
            model_name='roletemplateschedule',
            name='scheme',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='RoleTemplateSlot',
        ),
        migrations.AddField(
            model_name='roletemplateemployeerelation',
            name='template_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='frate.roletemplateschedule'),
        ),
    ]
