# Generated by Django 4.1.7 on 2023-06-17 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0018_roletemplateemployeerelation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roletemplateschedule',
            name='scheme',
        ),
        migrations.CreateModel(
            name='RotatingRtsSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_id', models.PositiveSmallIntegerField()),
                ('type', models.CharField(max_length=1)),
                ('role_template_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='frate.roletemplateschedule')),
                ('shifts', models.ManyToManyField(related_name='rotating_rts_slots', to='frate.shift')),
            ],
            options={
                'ordering': ['sd_id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OffRtsSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_id', models.PositiveSmallIntegerField()),
                ('type', models.CharField(max_length=1)),
                ('role_template_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='frate.roletemplateschedule')),
            ],
            options={
                'ordering': ['sd_id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericRtsSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_id', models.PositiveSmallIntegerField()),
                ('type', models.CharField(max_length=1)),
                ('role_template_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='frate.roletemplateschedule')),
            ],
            options={
                'ordering': ['sd_id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DirectRtsSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_id', models.PositiveSmallIntegerField()),
                ('type', models.CharField(max_length=1)),
                ('role_template_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='frate.roletemplateschedule')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_rts_slots', to='frate.shift')),
            ],
            options={
                'ordering': ['sd_id'],
                'abstract': False,
            },
        ),
    ]
