# Generated by Django 4.1.7 on 2023-06-17 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0019_remove_roletemplateschedule_scheme_rotatingrtsslot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericrtsslot',
            name='role_template_schedule',
        ),
        migrations.RemoveField(
            model_name='offrtsslot',
            name='role_template_schedule',
        ),
        migrations.RemoveField(
            model_name='roletemplateemployeerelation',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='roletemplateemployeerelation',
            name='template_schedule',
        ),
        migrations.RemoveField(
            model_name='rotatingrtsslot',
            name='role_template_schedule',
        ),
        migrations.RemoveField(
            model_name='rotatingrtsslot',
            name='shifts',
        ),
        migrations.DeleteModel(
            name='DirectRtsSlot',
        ),
        migrations.DeleteModel(
            name='GenericRtsSlot',
        ),
        migrations.DeleteModel(
            name='OffRtsSlot',
        ),
        migrations.DeleteModel(
            name='RoleTemplateEmployeeRelation',
        ),
        migrations.DeleteModel(
            name='RotatingRtsSlot',
        ),
    ]
