# Generated by Django 4.1.7 on 2023-06-17 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0021_roletemplateschedule_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roletemplateschedule',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_templates', to='frate.department'),
        ),
    ]
