# Generated by Django 4.1.7 on 2023-06-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0022_alter_roletemplateschedule_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('abvr', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('short', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='shift',
            name='weekdays',
        ),
        migrations.AddField(
            model_name='shift',
            name='weekdays',
            field=models.ManyToManyField(related_name='shifts', to='frate.weekday'),
        ),
    ]
