# Generated by Django 4.1.7 on 2023-06-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0023_weekday_remove_shift_weekdays_shift_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekday',
            name='n',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
