# Generated by Django 4.1.7 on 2023-06-21 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0024_weekday_n'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weekday',
            options={'ordering': ['n']},
        ),
        migrations.AlterField(
            model_name='roletemplatescheduleslot',
            name='shifts',
            field=models.ManyToManyField(related_name='template_slots', to='frate.shift'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='weekday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='frate.weekday'),
        ),
    ]
