# Generated by Django 4.1.7 on 2023-06-21 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0025_alter_weekday_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='frate.timephase'),
        ),
    ]
