# Generated by Django 4.1.7 on 2023-06-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0026_alter_shift_phase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timephase',
            options={'ordering': ['end_time'], 'verbose_name': 'Phase', 'verbose_name_plural': 'Phases'},
        ),
        migrations.RemoveField(
            model_name='department',
            name='img_url',
        ),
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='img'),
        ),
    ]
