# Generated by Django 4.1.7 on 2023-06-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0027_alter_timephase_options_remove_department_img_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletemplateschedule',
            name='slug',
            field=models.SlugField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roletemplateschedule',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
