# Generated by Django 4.1.7 on 2023-06-21 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0029_remove_roletemplatescheduleslot_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roletemplatescheduleslot',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='frate.roleleaderslot'),
        ),
    ]
