# Generated by Django 4.1.7 on 2023-06-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0030_alter_roletemplatescheduleslot_leader'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoleTemplateSchedule',
            new_name='Role',
        ),
        migrations.RenameModel(
            old_name='RoleTemplateScheduleSlot',
            new_name='RoleSlot',
        ),
    ]
