# Generated by Django 4.1.7 on 2023-06-21 12:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0031_rename_roletemplateschedule_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekday',
            name='sd_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, null=True, size=None),
        ),
    ]
