# Generated by Django 4.1.7 on 2023-06-21 12:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0032_weekday_sd_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekday',
            name='sd_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
