# Generated by Django 4.1.7 on 2023-06-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0035_alter_weekday_sd_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekday',
            name='sd_ids',
        ),
    ]
