# Generated by Django 4.1.7 on 2023-06-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0036_remove_weekday_sd_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='week_count',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='roleslot',
            name='shifts',
            field=models.ManyToManyField(related_name='role_slots', to='frate.shift'),
        ),
    ]
