# Generated by Django 4.1.7 on 2023-06-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0037_role_active_alter_role_week_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='static/media/img'),
        ),
    ]
