# Generated by Django 4.1.7 on 2023-06-22 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0038_alter_department_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='streak_pref',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='role',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='frate.department'),
        ),
        migrations.AlterField(
            model_name='role',
            name='employees',
            field=models.ManyToManyField(related_name='roles', to='frate.employee'),
        ),
    ]
