# Generated by Django 4.1.7 on 2023-06-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0040_rename_role_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=''),
        ),
    ]
