# Generated by Django 4.1.7 on 2023-06-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0042_alter_employee_options_alter_roleslot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shifttraining',
            options={'ordering': ['rank'], 'verbose_name': 'Shift Training', 'verbose_name_plural': 'Shift Trainings'},
        ),
        migrations.AddField(
            model_name='shifttraining',
            name='rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
