# Generated by Django 4.1.7 on 2023-06-25 23:16

from django.db import migrations, models
import django.db.models.deletion
import frate.validators


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0043_alter_shifttraining_options_shifttraining_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='employees',
            field=models.ManyToManyField(related_name='roles', to='frate.employee', validators=[frate.validators.RoleEmployeeValidator]),
        ),
        migrations.AlterField(
            model_name='slot',
            name='employee',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='frate.employee', validators=[frate.validators.SlotOvertimeValidator]),
        ),
    ]
