# Generated by Django 4.1.7 on 2023-06-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0044_alter_role_employees_alter_slot_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='filled_by',
            field=models.CharField(blank=True, choices=[('U', 'User'), ('M', 'Model')], default='U', max_length=1, null=True),
        ),
    ]
