# Generated by Django 4.1.7 on 2023-06-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0045_slot_filled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='pto_max_week_window',
            field=models.PositiveSmallIntegerField(default=52),
        ),
    ]
