# Generated by Django 4.1.7 on 2023-06-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0047_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='enrolled_in_inequity_monitoring',
            field=models.BooleanField(default=False),
        ),
    ]
