# Generated by Django 4.1.7 on 2023-06-27 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0048_employee_enrolled_in_inequity_monitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='adjacent_rotating_slot_pref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frate.shift'),
        ),
    ]
