# Generated by Django 4.1.7 on 2023-07-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0049_shift_adjacent_rotating_slot_pref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='employees',
            field=models.ManyToManyField(related_name='roles', to='frate.employee'),
        ),
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
