# Generated by Django 4.1.7 on 2023-07-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0050_alter_role_employees_alter_role_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
