# Generated by Django 4.1.7 on 2023-07-02 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0052_alter_ptorequest_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_id', models.PositiveSmallIntegerField()),
                ('goal', models.PositiveSmallIntegerField()),
                ('hours', models.PositiveSmallIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='frate.employee')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='frate.version')),
            ],
            options={
                'ordering': ['pd_id', 'employee__last_name'],
            },
        ),
    ]
