# Generated by Django 4.1.7 on 2023-07-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0055_slot_hours_alter_payperiod_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='hours',
            field=models.IntegerField(default=0),
        ),
    ]
