# Generated by Django 4.1.7 on 2023-07-03 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0056_alter_slot_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='PtoSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(default=8)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pto_slots', to='frate.employee')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pto_slots', to='frate.ptorequest')),
                ('workday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pto_slots', to='frate.workday')),
            ],
        ),
    ]
