# Generated by Django 4.1.7 on 2023-07-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0058_ptoslot_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='payperiod',
            name='discrepancy',
            field=models.IntegerField(default=0),
        ),
    ]
