# Generated by Django 4.1.7 on 2023-07-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0059_payperiod_discrepancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotoption',
            name='level',
            field=models.CharField(choices=[('A', 'Assertive'), ('P', 'Preferred'), ('D', 'Deferent'), ('S', 'Swap In'), ('B', 'Blocked')], default='P', max_length=1),
        ),
    ]
