# Generated by Django 4.1.7 on 2023-07-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0060_alter_slotoption_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='department',
            name='pto_max_week_window',
            field=models.PositiveSmallIntegerField(default=52, help_text='Maximum number of weeks in the future that PTO can be requested'),
        ),
        migrations.AlterField(
            model_name='slotoption',
            name='level',
            field=models.CharField(choices=[('C', 'Current'), ('A', 'Assertive'), ('P', 'Preferred'), ('D', 'Deferent'), ('S', 'Swap In'), ('B', 'Blocked')], default='P', max_length=1),
        ),
    ]
