# Generated by Django 4.1.7 on 2023-07-08 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0063_versionscorecard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versionscorecard',
            name='version',
        ),
    ]
