# Generated by Django 4.1.7 on 2023-07-08 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0065_version_scorecard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='scorecard',
        ),
        migrations.AddField(
            model_name='versionscorecard',
            name='version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scorecard', to='frate.version'),
        ),
    ]
