# Generated by Django 4.1.7 on 2023-07-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0067_slot_allowed_as_streak_breakpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='percent',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='versionscorecard',
            name='n_empty_slots',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
