# Generated by Django 4.1.7 on 2023-07-11 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0068_alter_version_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payperiod',
            name='goal',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='period',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='frate.payperiod'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='on_deck',
            field=models.ManyToManyField(blank=True, editable=False, related_name='on_deck_days', to='frate.employee'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='on_pto',
            field=models.ManyToManyField(blank=True, editable=False, related_name='pto_days', to='frate.employee'),
        ),
    ]
