# Generated by Django 4.1.7 on 2023-07-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0071_preferredhoursguide'),
    ]

    operations = [
        migrations.AddField(
            model_name='payperiod',
            name='fill_options',
            field=models.ManyToManyField(blank=True, editable=False, to='frate.slotoption'),
        ),
        migrations.AlterField(
            model_name='payperiod',
            name='discrepancy',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
