# Generated by Django 4.1.7 on 2023-07-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0072_payperiod_fill_options_alter_payperiod_discrepancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='slot_type',
        ),
        migrations.AddField(
            model_name='slot',
            name='exceeds_streak_pref',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='streak',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
