# Generated by Django 4.1.7 on 2023-07-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0074_slotoption_week_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotoption',
            name='level',
        ),
        migrations.AddField(
            model_name='slotoption',
            name='has_next_turnaround_block',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='slotoption',
            name='has_prev_turnaround_block',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='slotoption',
            name='has_pto_block',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='slotoption',
            name='has_same_day_block',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='slotoption',
            name='has_tdo_block',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
