# Generated by Django 4.1.7 on 2023-07-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0075_remove_slotoption_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotoption',
            name='has_block',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
