# Generated by Django 4.1.7 on 2023-07-11 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0076_slotoption_has_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferredhoursguide',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred_hours_guides', to='frate.version'),
        ),
    ]
