# Generated by Django 4.1.7 on 2023-07-11 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0077_preferredhoursguide_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDayToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('DECK', 'On Deck'), ('PTO', 'PTO'), ('TDO', 'Templated Off'), ('SLOT', 'In Slot')], default='DECK', max_length=4)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frate.employee')),
                ('workday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frate.workday')),
            ],
            options={
                'unique_together': {('employee', 'workday')},
            },
        ),
    ]
