# Generated by Django 4.1.7 on 2023-07-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0078_employeedaytoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferredhoursguide',
            name='end_date',
        ),
    ]
