# Generated by Django 4.1.7 on 2023-08-02 09:41

from django.db import migrations, models
import django.db.models.deletion
import frate.validators


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0080_remove_employeedaytoken_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='period',
        ),
        migrations.AlterField(
            model_name='slot',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='frate.employee', validators=[frate.validators.SlotOvertimeValidator]),
        ),
        migrations.AlterField(
            model_name='slot',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='versionscorecard',
            name='n_empty_slots',
            field=models.IntegerField(editable=False),
        ),
    ]
