# Generated by Django 4.1.7 on 2023-08-02 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0081_remove_slot_period_alter_slot_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='roles',
            field=models.ManyToManyField(related_name='schedules', to='frate.role'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='direct_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_template_for', to='frate.employee'),
        ),
    ]
