# Generated by Django 4.1.7 on 2023-08-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0082_schedule_roles_alter_slot_direct_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='payperiod',
            name='slots',
            field=models.ManyToManyField(blank=True, related_name='periods', to='frate.slot'),
        ),
    ]
