# Generated by Django 4.1.7 on 2023-08-03 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0083_payperiod_slots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payperiod',
            old_name='slots',
            new_name='linked_slots',
        ),
        migrations.AddField(
            model_name='slot',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='frate.payperiod'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='frate.employee'),
        ),
    ]
