# Generated by Django 4.1.7 on 2023-08-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0084_rename_slots_payperiod_linked_slots_slot_period_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['workday__date', 'shift__start_time']},
        ),
        migrations.AlterField(
            model_name='workday',
            name='on_deck',
            field=models.ManyToManyField(blank=True, related_name='on_deck_days', to='frate.employee'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='on_pto',
            field=models.ManyToManyField(blank=True, related_name='pto_days', to='frate.employee'),
        ),
    ]
