# Generated by Django 4.1.7 on 2023-08-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0085_alter_slot_options_alter_workday_on_deck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='preference_percentile',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
