# Generated by Django 4.1.7 on 2023-08-04 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0086_slot_preference_percentile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleslot',
            name='type',
        ),
    ]
