# Generated by Django 4.1.7 on 2023-08-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0087_remove_roleslot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttraining',
            name='rank_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
