# Generated by Django 4.1.7 on 2023-08-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0088_shifttraining_rank_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionscorecard',
            name='n_untrained_slots',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
