# Generated by Django 4.1.7 on 2023-08-07 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0089_versionscorecard_n_untrained_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferredhoursguide',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_hours', to='frate.employee'),
        ),
        migrations.AlterField(
            model_name='preferredhoursguide',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred_hours', to='frate.version'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='direct_template',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_template_for', to='frate.employee'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='rotating_templates',
            field=models.ManyToManyField(blank=True, editable=False, related_name='rotating_template_for', to='frate.employee'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='on_deck',
            field=models.ManyToManyField(blank=True, editable=False, related_name='on_deck_days', to='frate.employee'),
        ),
    ]
