# Generated by Django 4.1.7 on 2023-08-07 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0090_alter_preferredhoursguide_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='direct_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_template_for', to='frate.employee'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='rotating_templates',
            field=models.ManyToManyField(blank=True, related_name='rotating_template_for', to='frate.employee'),
        ),
    ]
