# Generated by Django 4.1.7 on 2023-08-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0091_alter_slot_direct_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='hours',
        ),
    ]
