# Generated by Django 4.1.7 on 2023-08-08 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frate', '0094_remove_workday_on_deck'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_token_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='verification_token', to='frate.employee')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Verification Token',
                'verbose_name_plural': 'Profile Verification Tokens',
            },
        ),
    ]
