# Generated by Django 4.1.7 on 2023-08-08 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0095_profileverificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferredhoursguide',
            name='start_date',
        ),
    ]
