# Generated by Django 4.1.7 on 2023-08-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0096_remove_preferredhoursguide_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='relative_rank',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
