# Generated by Django 4.1.7 on 2023-08-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0098_shift_preference_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_niche',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shift',
            name='preference_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
