# Generated by Django 4.1.7 on 2023-08-10 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0099_shift_is_niche_alter_shift_preference_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileverificationtoken',
            options={'permissions': (('can_view', 'Can view Profile Verification Tokens'), ('can_create', 'Can create Profile Verification Tokens')), 'verbose_name': 'Profile Verification Token', 'verbose_name_plural': 'Profile Verification Tokens'},
        ),
    ]
