# Generated by Django 4.1.7 on 2023-08-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0100_alter_profileverificationtoken_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotoption',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='slotoption',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='payperiod',
            name='fill_options',
        ),
        migrations.AlterField(
            model_name='employee',
            name='pto_hours',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.DeleteModel(
            name='EmployeeDayToken',
        ),
        migrations.DeleteModel(
            name='SlotOption',
        ),
    ]
