# Generated by Django 4.1.7 on 2023-08-11 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0101_remove_slotoption_employee_remove_slotoption_slot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wk_id', models.IntegerField(default=0)),
                ('pd_id', models.IntegerField(default=0)),
                ('week_hours', models.IntegerField(default=0)),
                ('period_hours', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frate.employee')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frate.slot')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'ordering': ['employee', 'slot'],
                'unique_together': {('employee', 'slot')},
            },
        ),
    ]
