# Generated by Django 4.1.7 on 2023-08-11 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0102_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='std_hours_override',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='option',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='frate.employee'),
        ),
        migrations.AlterField(
            model_name='option',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='frate.slot'),
        ),
        migrations.CreateModel(
            name='HoursOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours_overrides', to='frate.employee')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_hours_overrides', to='frate.schedule')),
            ],
        ),
    ]
