# Generated by Django 4.1.7 on 2023-08-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0103_employee_std_hours_override_alter_option_employee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['slot', '-entitled', '-discrepancy'], 'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
        migrations.AddField(
            model_name='option',
            name='discrepancy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='option',
            name='entitled',
            field=models.BooleanField(default=False),
        ),
    ]
