# Generated by Django 4.1.7 on 2023-08-11 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0104_alter_option_options_option_discrepancy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='pay_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='frate.payperiod'),
        ),
    ]
