# Generated by Django 4.1.7 on 2023-08-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0105_option_pay_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='pd_id',
        ),
        migrations.RemoveField(
            model_name='option',
            name='period_hours',
        ),
        migrations.RemoveField(
            model_name='option',
            name='week_hours',
        ),
        migrations.RemoveField(
            model_name='option',
            name='wk_id',
        ),
    ]
