# Generated by Django 4.1.7 on 2023-08-15 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0106_remove_option_pd_id_remove_option_period_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='period_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='option',
            name='week_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payperiod',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='frate.employee'),
        ),
        migrations.AlterField(
            model_name='payperiod',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='frate.version'),
        ),
    ]
