# Generated by Django 4.1.7 on 2023-08-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0107_option_period_hours_option_week_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='is_viable',
            field=models.BooleanField(default=True),
        ),
    ]
