# Generated by Django 4.1.7 on 2023-08-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0108_option_is_viable'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='must_trade',
            field=models.BooleanField(default=False),
        ),
    ]
