# Generated by Django 4.1.7 on 2023-08-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frate', '0109_option_must_trade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name', 'department__name']},
        ),
        migrations.AddField(
            model_name='timephase',
            name='color',
            field=models.CharField(blank=True, choices=[('amber', 'Amber'), ('blue', 'Blue'), ('sky', 'Sky'), ('teal', 'Teal'), ('green', 'Green'), ('indigo', 'Indigo'), ('purple', 'Purple')], max_length=20, null=True),
        ),
    ]
