# Generated by Django 4.1.7 on 2023-08-16 06:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frate", "0112_option_fill_method"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="option",
            options={
                "ordering": ["slot", "-entitled", "discrepancy"],
                "verbose_name": "Option",
                "verbose_name_plural": "Options",
            },
        ),
    ]
