# Generated by Django 4.1.7 on 2023-08-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frate", "0113_alter_option_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="option",
            name="fill_method",
            field=models.CharField(
                choices=[
                    ("P", "Pick Up"),
                    ("T", "Trade"),
                    ("O", "Pick Up Into Overtime"),
                    ("B", "Break PTO"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
