# Generated by Django 4.1.7 on 2023-08-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frate", "0114_option_affinity_score_alter_option_fill_method"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="option",
            options={
                "ordering": ["slot", "-entitled", "-affinity_score"],
                "verbose_name": "Option",
                "verbose_name_plural": "Options",
            },
        ),
        migrations.AlterField(
            model_name="option",
            name="fill_method",
            field=models.CharField(
                choices=[
                    ("P", "Pick Up"),
                    ("T", "Trade"),
                    ("O", "Pick Up Into Overtime"),
                    ("B", "Break PTO"),
                    ("D", "Break TDO"),
                ],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="payperiod",
            name="discrepancy",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payperiod",
            name="goal",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
