# Generated by Django 4.1.7 on 2023-08-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frate", "0115_alter_option_options_alter_option_fill_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payperiod",
            name="goal",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
