# Generated by Django 4.1.7 on 2023-08-23 07:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frate", "0117_alter_payperiod_goal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payperiod",
            name="linked_slots",
        ),
    ]
