# Generated by Django 4.1.7 on 2023-08-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frate", "0118_remove_payperiod_linked_slots"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payperiod",
            options={"ordering": ["pd_id", "discrepancy", "employee"]},
        ),
        migrations.AddField(
            model_name="option",
            name="marked_as_off",
            field=models.BooleanField(default=False),
        ),
    ]
