# Generated by Django 4.1.7 on 2023-08-26 08:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frate", "0119_alter_payperiod_options_option_marked_as_off"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payperiod",
            options={"ordering": ["pd_id", "-discrepancy", "employee"]},
        ),
    ]
