# Generated by Django 4.1.7 on 2023-08-26 08:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frate", "0120_alter_payperiod_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Option",
        ),
    ]
