# Generated by Django 4.1.7 on 2023-08-27 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("frate", "0122_versionemployee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="versionemployee",
            name="per_period_goal",
        ),
        migrations.RemoveField(
            model_name="versionemployee",
            name="per_period_min",
        ),
        migrations.AddField(
            model_name="versionemployee",
            name="discrepancy",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="versionemployee",
            name="hours",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="versionemployee",
            name="overtime",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="versionemployee",
            name="slots",
            field=models.ManyToManyField(
                related_name="version_employees", to="frate.slot"
            ),
        ),
        migrations.AlterField(
            model_name="versionemployee",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="version_employees",
                to="frate.employee",
            ),
        ),
        migrations.AlterField(
            model_name="versionemployee",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="version_employees",
                to="frate.version",
            ),
        ),
    ]
