# Generated by Django 4.1.7 on 2023-08-29 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("frate", "0125_solutionattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="versionscorecard",
            name="n_exceeds_streak",
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="versionscorecard",
            name="n_overtime_hours",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="versionscorecard",
            name="n_empty_slots",
            field=models.PositiveSmallIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="versionscorecard",
            name="n_untrained_slots",
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="versionscorecard",
            name="version",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scorecard",
                to="frate.version",
            ),
            preserve_default=False,
        ),
    ]
