# Generated by Django 4.1.7 on 2023-08-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frate", "0126_versionscorecard_n_exceeds_streak_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="versionscorecard",
            name="n_overtime_hours",
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
